### ISSUE TITLE
QA issues with the repo

### ISSUE THREAD

**Issue by mgorny** [sjnewbury/gentoo-playground#2]
There's [Gentoo bug #613042](https://bugs.gentoo.org/show_bug.cgi?id=613042) open w/ QA issues with the repo. Please fix them urgently (note that you may need to wait 30 minutes after push and refresh the linked report to see if there are no more issues) or at least respond to the bug. Otherwise, the repo will be removed.

**Comment by sjnewbury** [comment]
I replied on the Gentoo bug, but again apologies for the poor state of this repo.  It does have some things in it people would probably find useful, but I've not been keeping on top of maintenance at all.

I'll locally move everything out, then just put back what I'm currently maintaining.  I should have done it a while ago!

**Comment by sjnewbury** [comment]
Running everything through repoman now, so hopefully no more issues... 4 years of neglect... eeek!
